// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen". 
 import tsconfigPaths from 'vite-tsconfig-paths'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  plugins: [tsconfigPaths()],
  test: {
    // ...
  },
})
 
    